---
title: "griis"
author: "Fonti Kar"
date: "2022-11-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, data.table)
```

### Read in AFD

```{r}
afd_species <- read_csv("output/afd_splist_full.csv")
all_species <- afd_species$VALID_NAME 
```

### Read in most updated GRIIS list

Currently this list is not on ALA website

```{r}
distribution <- fread("data/dwca-griis-australia-v1.6/distribution.txt")
species <- fread("data/dwca-griis-australia-v1.6/speciesprofile.txt")
taxa <- fread("data/dwca-griis-australia-v1.6/taxon-edited.txt", fill = TRUE)
```

### Create a GRIIS list

```{r}
griis_list <- taxa |>  
  full_join(distribution, by = "id") |>  
  full_join(species, by = "id")
```
  
### Clean up the variables

```{r}
griis_ala_raw <- as.data.frame(search_taxa(griis_list$scientificName))

# clean up search_taxa() results by noIssue
griis_ala_tidy <- griis_ala_raw |>  
  filter(issues == "noIssue",
         !is.na(species)) |>  
  dplyr::select(search_term, taxon_concept_id, scientific_name, scientific_name_authorship)
```

### Cross matching AFD to updated GRIIS list  
```{r}
message(cat("number of AFD species listed in GRIIS: "),
        length(which(afd_species$VALID_NAME %in% griis_ala_tidy$scientific_name)))

message("AFD species in GRIIS - Global Register of Introduced and Invasive Species - Australia: ")
updated_griis_afd <- afd_species$VALID_NAME[which(afd_species$VALID_NAME %in% griis_ala_tidy$scientific_name)]
```

### Cross matching AFD to old GRIIS list

```{r}
griis_species <- read.csv("data/GRIIS_Global_Register_of_Introduced_and_Invasive_Species_Australia.csv")

message(cat("number of AFD species listed in GRIIS: "),
        length(which(afd_species$VALID_NAME %in% griis_species$Supplied.Name)))

message("AFD species in GRIIS - Global Register of Introduced and Invasive Species - Australia: ")
old_griis_afd <- afd_species$VALID_NAME[which(afd_species$VALID_NAME %in% griis_species$Supplied.Name)]
```

### Difference between found matches

```{r}
dplyr::setdiff(updated_griis_afd, old_griis_afd)
data.frame(dplyr::setdiff(old_griis_afd, updated_griis_afd)) %>% search_taxa() # Not in ALA
```

