---
title: "IRMNG"
author: "Fonti Kar"
date: "2022-10-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
#install.packages("pacman")
pacman::p_load(dplyr, janitor, galah, stringr, tidyverse, arrow, stringr, data.table)
```

## Read in data

```{r}
# Taxonomic info
irmng_taxa <- fread("data/IRMNG/irmng_taxon.txt")

head(irmng_taxa)
names(irmng_taxa)
dim(irmng_taxa)

# Species profile
irmng_sp <- fread("data/IRMNG/irmng_speciesprofile.txt")

head(irmng_sp)
names(irmng_sp)
dim(irmng_sp)

```

## Filter list down to only Animalia 

```{r}
irmng_taxa |> 
  filter(kingdom == "Animalia") |> 
  dim()

irmng_taxa |> 
  filter(kingdom == "Animalia") -> animalia_irmng
```

## Exclude everything "Vertebrata"

```{r}
# Tally of counts for each phylum
arrange(animalia_irmng, phylum) |> 
  pull(phylum) |>  tabyl()

# Invertebrate phylums
invert_phy <- c("Porifera",
                "Ctenophora",
                "Cnidaria", 
                "Xenacoelomorpha", 
                "Platyhelminthes",
                "Annelida",
                "Arthropoda",
                "Mollusca",
                "Nematoda",
                "Rotifera",
                "Tardigrada",
                "Scalidophora",
                "Lophophorata",
                "Onychophora",
                "Chaetognatha",
                "Nematomorpha",
                "Nemertea",
                "Placozoa",
                "Loricifera",
                "Echinodermata",
                "Hemichordata",
                "Acoelomorpha", 
                "Brachiopoda",
                "Bryozoa", 
                "Entoprocta", 
                "Phoronida", 
                "Xenoturbellida") 

animalia_irmng |> 
  filter(phylum %in% invert_phy) |> 
  dim()

# Tally of counts for orders in Chordata
animalia_irmng |> 
  filter(phylum == "Chordata") |> 
  pull(order) |>  unique() -> chordata_orders

# Only Amphioxiformes in list
str_subset(string = chordata_orders, pattern = paste(within_chords, collapse = "|"), )

# Within Chordata
within_chords <-c("Amphioxiformes",
                  "Tunicata")

animalia_irmng |> 
  filter(order %in% within_chords) |> 
  dim()

# Filter down to invertebrates
animalia_irmng |> 
  filter(phylum %in% invert_phy | order %in% within_chords) |> dim()

animalia_irmng |> 
  filter(phylum %in% invert_phy | order %in% within_chords) -> invert_irmng
```

## Merge in taxonID

```{r}
invert_irmng |> 
  left_join(irmng_sp, by = "taxonID") -> invert_irmng
```

## Filter is.Marine

```{r}
invert_irmng |> 
  filter(isMarine == TRUE) |> 
  dim() 

invert_irmng |> 
  filter(isMarine == TRUE) -> marine_invert_irmng
```

## Check of overlap

```{r}
afd_species <- read_csv("output/afd_splist_full.csv")

names(afd_species)
dim(afd_species)

lower_afd <- afd_species

# Change format of text
lower_afd |> mutate(PHYLUM = stringr::str_to_title(PHYLUM),
                    CLASS = stringr::str_to_title(CLASS),
                    ORDER = stringr::str_to_title(ORDER),
                    FAMILY = stringr::str_to_title(FAMILY),
                    GENUS = stringr::str_to_title(GENUS)) -> lower_afd

# Remove suffix "(awaiting allocation)" and keep first word for now
x <- "(awaiting allocation)"
writeLines(x)
awaiting_class <- str_subset(string = unique(marine_invert_irmng$class), pattern = x) 


# Do awaiting_class exist as classes themselves
 marine_invert_irmng |> mutate(class = ifelse()) word(awaiting_class) 

marine_invert_irmng |> 
  filter(class %in% awaiting_class) |> dim() #Excluding


marine_invert_irmng |> dim()
# Overlap with Class
marine_invert_irmng$class |> tabyl()

lower_afd |> filter(PHYLUM %in% unique(marine_invert_irmng$phylum)) 

lower_afd |> filter(! PHYLUM %in% unique(marine_invert_irmng$phylum)) |> dim()

lower_afd |> filter(! PHYLUM %in% unique(marine_invert_irmng$phylum)) |> pull(PHYLUM)

```


## Export as .csv

```{r}
write.csv(invert_irmng, "data/invert_irmng.csv")
fwrite(invert_irmng, "data/invert_irmng.txt", row.names = FALSE)
```


