---
title: "Concaveman"
author: "Fonti Kar"
date: "2023-02-15"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(galah, sf, ozmaps, ggforce, ggmap, tidyverse, here, skimr, readr, concaveman)

```

### Read in data

```{r}
#inverts <- read_csv(here("data", "inverts", "invertebrate.data.fixed.csv"))
inverts <- read_csv(here("ignore", "Curated_Plant_and_Invertebrate_Data_for_Bushfire_Modelling", "invertebrate.data.csv"))
vplants <- read_csv(here("ignore","Curated_Plant_and_Invertebrate_Data_for_Bushfire_Modelling", "vascularplant.data.csv"))
fire_overlap_inverts <- read_csv(here("ignore", "data", "inverts", "Fire_overlap_results_2021-06-24.csv"))

str(inverts)
skim(inverts)
skim(fire_overlap_inverts)
```

### filtering fire overlap data 

```{r}
# keep only useful columns and sort 
fire_overlap_inverts_short<- fire_overlap_inverts %>%
  select(scientificName, 
         class,
         order,
         family,
         Overlap_Points_Fire345_GEEBAM2_as_unburnt,
         Overlap_Points_Fire2345_GEEBAM2_as_burnt,
         Overlap_Points_Severe_Fire45,
         Total_fire_points,
         Occurrence_Points, 
         Total_fire_polygon, 
         Species_Polygon,
         Overlap_Polygons_Fire2345_GEEBAM2_as_burnt,
         EOO, 
         AOO)  %>% 
  rename(scientific_name = scientificName)

# get most fire impacted species per family
  max_burnt_fam<-fire_overlap_inverts_short%>%
    group_by(family)%>%
    slice_max(order_by = Overlap_Polygons_Fire2345_GEEBAM2_as_burnt,
              n = 1) %>%
    select(scientific_name, family, Overlap_Polygons_Fire2345_GEEBAM2_as_burnt) %>%
    filter(Overlap_Polygons_Fire2345_GEEBAM2_as_burnt>25)

  max_burnt_fam %>% ungroup() %>% slice(1:5) %>% pull(scientific_name) -> topburnt_family
  
  # check it has worked  
fire_overlap_inverts_short %>%
  filter(family == "acrididae") %>%
  slice_max(Overlap_Polygons_Fire2345_GEEBAM2_as_burnt,
            n = 10) %>%
  select(scientific_name, family, Overlap_Polygons_Fire2345_GEEBAM2_as_burnt)
# print(n = 100)

##max per class

  max_burnt_class<-fire_overlap_inverts_short%>%
    group_by(class)%>%
    slice_max(order_by = Overlap_Polygons_Fire2345_GEEBAM2_as_burnt,
              n = 1) %>%
    select(scientific_name, class, Overlap_Polygons_Fire2345_GEEBAM2_as_burnt) %>%
    filter(Overlap_Polygons_Fire2345_GEEBAM2_as_burnt>25)

  # check it has worked  
fire_overlap_inverts_short %>%
  filter(family == "acrididae") %>%
  slice_max(Overlap_Polygons_Fire2345_GEEBAM2_as_burnt,
            n = 10) %>%
  select(scientific_name, family, Overlap_Polygons_Fire2345_GEEBAM2_as_burnt)

  
# merge data-frames together to keep only most impacted species per family in inverts data 

inverts_fire<-merge(max_burnt_fam, inverts, by = 'scientific_name') %>%
  select(scientific_name, 
         family.x, 
         Overlap_Polygons_Fire2345_GEEBAM2_as_burnt, 
         record_id, 
         class, 
         year, 
         latitude, 
         longitude)%>%
  rename(family = family.x)
 

inverts_fire_class<-merge(max_burnt_class, inverts, by = 'scientific_name') 
  
inverts_fire_class<-inverts_fire_class%>%
  select(scientific_name, 
         Overlap_Polygons_Fire2345_GEEBAM2_as_burnt, 
         record_id, 
         class.x, 
         year, 
         latitude,
         longitude) %>%
    rename(class = class.x)

```


### Summaries of all taxonomic levels

Plot by class might be better! Each family is only represented by 1 taxa

```{r}
clean_inv %>% 
  group_by(class) %>% 
  summarise(n_sp = length(unique(scientific_name))) %>% 
  arrange(-n_sp)  %>% 
  print(n = 50) 

clean_inv %>% 
  group_by(family) %>% 
  summarise(n_sp = length(unique(scientific_name))) %>%
  arrange(-n_sp) 

## Other class
other_class <- clean_inv %>% 
  group_by(class) %>% 
  summarise(n_sp = length(unique(scientific_name))) %>%
  filter(n_sp <= 10 | is.na(class)) %>% 
  pull(class)

## Case study
clean_inv %>% 
  filter(class == "Arachnida", 
         family == "Salticidae") %>% 
  group_by(scientific_name) %>% 
  summarise(n()) %>% 
  arrange(-`n()`) %>% slice(1:10) %>% 
  pull(scientific_name) -> top10jspiders #Top 5 species
``` 

### Create new class variable

```{r}
clean_inv <- clean_inv %>% 
  mutate(plot_class = ifelse(class %in% other_class, "Other", class)) 

clean_inv %>% 
  group_by(plot_class) %>% 
  summarise(n_sp = length(unique(scientific_name))) %>% 
  arrange(-n_sp)  %>% 
  print(n = 50)  # Check if we can see "Other"
```

### Try plotting these funky hulls for top10 spiders as an example

#### Filter data and make sf object
```{r}
spiderdat <- clean_inv %>% 
  filter(scientific_name %in% top10jspiders)

spider_sf<- spiderdat %>% 
  t_as_sf(coords = c("longitude", "latitude"), crs = 4326)

##try plotting most impacted species 
fire_sf<- inverts_fire %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)


```

#### Make base map components geom_mark_hulls

```{r}
aus <- st_transform(ozmap_country, 4326)

ggplot() + 
  geom_sf(data = aus, colour = "black", fill = "white") +
  geom_sf(data = spider_sf %>% filter(!scientific_name %in% c("Apricia jovialis", 
                                                              "Apricia bracteata",
                                                              "Pellenes bitaeniata"))) +
  geom_mark_hull(spiderdat %>% filter(!scientific_name %in% c("Apricia jovialis", 
                                                              "Apricia bracteata",
                                                            "Pellenes bitaeniata")), mapping = aes(x = longitude, y = latitude,
                                fill = scientific_name, label = scientific_name), alpha = 0.2, con.cap = 0)  + 
  theme_minimal() +
  theme(legend.position = "none")

#silly plot

 #HULLS<- ggplot() + 
# geom_sf(data = aus, colour = "black", fill = "white") +
#  geom_sf(data = fire_sf %>% filter(!scientific_name %in% c("Agathodesmus carorum", 
   #                                                           "Argulus japonicus",
   #                                                           "Euastacus guwinus"))) +
#  geom_mark_hull(inverts_fire %>% filter(!scientific_name %in% c("Agathodesmus carorum", 
  #                                                            "Argulus japonicus",
  #                                                          "Euastacus guwinus")), mapping = aes(x = longitude, y = latitude,
  #                              fill = scientific_name, label = scientific_name), alpha = 0.2, con.cap = 0)  + 
  #  lims(x = c(100, 180))+
 # theme_minimal() +
 # theme(legend.position = "none")
 
# ggsave("hullsplot.pdf", HULLS, width = 42, height = 29.7, units = "cm" )
```

### Trying beautiful stamen maps

```{r}
map <- get_stamenmap( bbox = c(left = 110, bottom = -45, right = 157, top = -9.5), zoom = 5, maptype = "watercolor")

ggmap(map) + 
geom_point(data = inverts_fire_class, aes(x = longitude, y = latitude,
                                         # size = Overlap_Polygons_Fire2345_GEEBAM2_as_burnt,
                                          colour = Overlap_Polygons_Fire2345_GEEBAM2_as_burnt),
           alpha = 1) + 
geom_mark_hull(inverts_fire_class,
                 mapping = aes(x = longitude, y = latitude, group = scientific_name, fill = scientific_name),
                 alpha = 0.2, con.cap = 0, concavity = 2, 
                 expand = unit(2.5, "mm"), radius = unit(2.5, "mm")) +
  scale_color_gradientn(colours = c("#EFD175", "#C56614", "#B33317")) + 
  guides() + 
  theme(
    plot.title = element_text(colour = "orange"), 
    panel.border = element_rect(colour = "grey", fill=NA, size=2),
    legend.position = "bottom") + 
  facet_wrap(~class)


# geom_mark_hull(spiderdat %>% filter(scientific_name %in% c("Maratus mungaich", 
#                                                              "Maratus vespertilio",
#                                                              "Hypoblemum scutulatum",
#                                                              "Afraflacilla stridulator")), 
#                  mapping = aes(x = longitude, y = latitude, group = scientific_name, label = scientific_name),
#                  alpha = 0.2, con.cap = 0, concavity = 2) +

```


### Read in fire layer

```{r}
fname <- here("ignore", "NIAFED_v20200623", "NIAFED_20190701_20200622_v20200623.shp")
fire <- st_read(fname)
fire_2 <- st_transform(fire, crs = 4326)

fire_2[1]

ggplot() + 
  geom_sf(data = aus, colour = "black", fill = "white") + 
  geom_sf(data = fire_2, color = "mediumorchid4") + 
  geom_sf(data = spider_sf %>% filter(!scientific_name %in% c("Apricia jovialis", 
                                                              "Apricia bracteata",
                                                              "Pellenes bitaeniata"))) +
  geom_mark_hull(spiderdat %>% filter(!scientific_name %in% c("Apricia jovialis", 
                                                              "Apricia bracteata",
                                                            "Pellenes bitaeniata")), mapping = aes(x = longitude, y = latitude,
                                group = scientific_name), alpha = 0.2, con.cap = 0)  + 
  theme_minimal() +
  theme(legend.position = "none")
```





