---
title: "Investigating WORMS"
author: "Fonti Kar"
date: "2022-08-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("worrms") https://docs.ropensci.org/worrms/index.html

pacman::p_load(tidyverse, worrms)
```

Read in AFD list

```{r}
afd_taxonomy <- read_csv("output/afd_species_clean.csv")
afd_species <- unique(afd_taxonomy$VALID_NAME) 
```

## A small test

```{r}
set.seed(8)

x <- sample(afd_species, 50) 

test_alltypes_ls <- wm_records_names(x)
test_alltypes_df <- bind_rows(test_alltypes_ls)

test_df |> select(scientificname, starts_with("is")) 

x[which(x %in% marine_sp)] # Seems to work well! 

```

## Lets expand it

```{r}
# If I do full list, it runs out of memory, reducing list to 500, 200, 100 seems to work
# afd_species_ls <- wm_records_names(afd_species) |> bind_rows() 

afd_species_ls <- wm_records_names(afd_species[1:100]) |> bind_rows()
```

```{r}
## Code for for loop to query their API - slow, 1hr 
afd_species <- unique(afd_taxonomy$VALID_NAME) 

afd_species_chunks <- split(afd_species, ceiling(seq_along(afd_species)/120))

for (i in 1:length(afd_species_chunks)) {
  
message(cat("Working on", names(afd_species_chunks)[i], "/", length(afd_species_chunks)))
  
try(worrms::wm_records_names(afd_species_chunks[[i]]) -> tmp)
    
    tmp |> bind_rows() -> afd_marine
    
    if(nrow(afd_marine) > 0){
    filenm <- paste0("output/rds/afd_marine", "_", names(afd_species_chunks)[i], ".rds")
  
    saveRDS(afd_marine, filenm)
  }
  
}
```

## Workflow to exclude marine species from AFD checklist

```{r}
afd_species_ls |> pull(scientificname) -> marine_afd

## Excluding the marine species in VALID_NAME
afd_taxonomy |> filter(! VALID_NAME %in% marine_afd) -> afd_taxonomy_nomarine
```

## Read in all the .rds and bind

```{r}
dir <- "output/rds/"
files <- list.files("output/rds/") 
files |> length()
filenms <- paste0(dir, files)

#myfiles = lapply(filenms, readRDS)

myfiles <- purrr::map(filenms, 
                     readRDS) |> bind_rows()

#write.csv(myfiles, )
myfiles <- read.csv("output/afd_marine_sp.csv")

```

## Exclude marine species found by WoRMs by VALID_NAME

```{r}
myfiles$scientificname |> length()
myfiles$valid_name |> length()

(myfiles$scientificname == myfiles$valid_name) |> janitor::tabyl()

afd_taxonomy |> filter(! VALID_NAME %in% myfiles$scientificname) # 90,230
afd_taxonomy |> filter(! VALID_NAME %in% myfiles$valid_name) # 92,730

afd_taxonomy$VALID_NAME
```
 
